In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [43]:
df = pd.read_csv('movies_metadata.csv')

In [44]:
df

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,NaN,0.0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1.0
45462,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",NaN,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0.0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,NaN,Century of Birthing,False,9.0,3.0
45463,False,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0.0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6.0
45464,False,NaN,0,[],NaN,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0.0,87.0,[],Released,NaN,Satan Triumphant,False,0.0,0.0
45465,False,NaN,0,[],NaN,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0.0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Queerama,False,0.0,0.0

#EDA & Preproccesing

In [45]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [46]:
df.columns.size

24

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [48]:
df.shape

(45466, 24)

In [49]:
df.describe()

            revenue       runtime  vote_average    vote_count
count  4.546000e+04  45203.000000  45460.000000  45460.000000
mean   1.120935e+07     94.128199      5.618207    109.897338
std    6.433225e+07     38.407810      1.924216    491.310374
min    0.000000e+00      0.000000      0.000000      0.000000
25%    0.000000e+00     85.000000      5.000000      3.000000
50%    0.000000e+00     95.000000      6.000000     10.000000
75%    0.000000e+00    107.000000      6.800000     34.000000
max    2.787965e+09   1256.000000     10.000000  14075.000000

In [50]:
df.duplicated().sum()

np.int64(13)

In [51]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [52]:
df = df.drop_duplicates().reset_index(drop=True)

In [53]:
df.duplicated().sum()

np.int64(0)

In [54]:
df =df[[
    'title',
    'genres',
    'overview',
    'vote_average',
    'vote_count',
    'popularity',
    'production_companies',
    'tagline'
]]

In [55]:
df.isnull().sum()

title                       6
genres                      0
overview                  954
vote_average                6
vote_count                  6
popularity                  5
production_companies        3
tagline                 25045
dtype: int64

In [56]:
df = df.dropna(subset=['title'])

In [57]:
df.isnull().sum()

title                       0
genres                      0
overview                  954
vote_average                0
vote_count                  0
popularity                  0
production_companies        0
tagline                 25039
dtype: int64

In [58]:
df['overview'] = df['overview'].fillna('')

In [59]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [60]:
import ast
df['genres']=df['genres'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))

In [61]:
df.isnull().sum()

title                       0
genres                      0
overview                    0
vote_average                0
vote_count                  0
popularity                  0
production_companies        0
tagline                 25039
dtype: int64

In [62]:
df['tagline'] = df['tagline'].fillna('')

In [63]:
df.isnull().sum()

title                   0
genres                  0
overview                0
vote_average            0
vote_count              0
popularity              0
production_companies    0
tagline                 0
dtype: int64

In [64]:
df

,title,genres,overview,vote_average,vote_count,popularity,production_companies,tagline
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",7.7,5415.0,21.946943,"[{'name': 'Pixar Animation Studios', 'id': 3}]",
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,6.9,2413.0,17.015539,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...",Roll the dice and unleash the excitement!
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,6.5,92.0,11.7129,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...",Still Yelling. Still Fighting. Still Ready for...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",6.1,34.0,3.859495,[{'name': 'Twentieth Century Fox Film Corporat...,Friends are the people who let you be yourself...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,5.7,173.0,8.387519,"[{'name': 'Sandollar Productions', 'id': 5842}...",Just When His World Is Back To Normal... He's ...
...,...,...,...,...,...,...,...,...
45448,Subdue,Drama Family,Rising and falling between a man and woman.,4.0,1.0,0.072051,[],Rising and falling between a man and woman
45449,Century of Birthing,Drama,An artist struggles to finish his work while a...,9.0,3.0,0.178241,"[{'name': 'Sine Olivia', 'id': 19653}]",
45450,Betrayal,Action Drama Thriller,"When one of her hits goes wrong, a professiona...",3.8,6.0,0.903007,"[{'name': 'American World Pictures', 'id': 6165}]",A deadly game of wits.
45451,Satan Triumphant,,"In a small town live two brothers, one a minis...",0.0,0.0,0.003503,"[{'name': 'Yermoliev', 'id': 88753}]",
45452,Queerama,,50 years after decriminalisation of homosexual...,0.0,0.0,0.163015,[],

In [65]:
df.iloc[0]['production_companies']

"[{'name': 'Pixar Animation Studios', 'id': 3}]"

In [66]:
import ast
df['production_companies']=df['production_companies'].apply(lambda x:" ".join([i['name'] for i in ast.literal_eval(x)]))

In [67]:
df

,title,genres,overview,vote_average,vote_count,popularity,production_companies,tagline
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",7.7,5415.0,21.946943,Pixar Animation Studios,
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,6.9,2413.0,17.015539,TriStar Pictures Teitler Film Interscope Commu...,Roll the dice and unleash the excitement!
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,6.5,92.0,11.7129,Warner Bros. Lancaster Gate,Still Yelling. Still Fighting. Still Ready for...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",6.1,34.0,3.859495,Twentieth Century Fox Film Corporation,Friends are the people who let you be yourself...
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,5.7,173.0,8.387519,Sandollar Productions Touchstone Pictures,Just When His World Is Back To Normal... He's ...
...,...,...,...,...,...,...,...,...
45448,Subdue,Drama Family,Rising and falling between a man and woman.,4.0,1.0,0.072051,,Rising and falling between a man and woman
45449,Century of Birthing,Drama,An artist struggles to finish his work while a...,9.0,3.0,0.178241,Sine Olivia,
45450,Betrayal,Action Drama Thriller,"When one of her hits goes wrong, a professiona...",3.8,6.0,0.903007,American World Pictures,A deadly game of wits.
45451,Satan Triumphant,,"In a small town live two brothers, one a minis...",0.0,0.0,0.003503,Yermoliev,
45452,Queerama,,50 years after decriminalisation of homosexual...,0.0,0.0,0.163015,,

In [68]:
df['tags'] = df['overview'] + " " + df['genres'] + " " + df['tagline']+" "+df['production_companies']

In [69]:
df

,title,genres,overview,vote_average,vote_count,popularity,production_companies,tagline,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",7.7,5415.0,21.946943,Pixar Animation Studios,,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,6.9,2413.0,17.015539,TriStar Pictures Teitler Film Interscope Commu...,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,6.5,92.0,11.7129,Warner Bros. Lancaster Gate,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",6.1,34.0,3.859495,Twentieth Century Fox Film Corporation,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,5.7,173.0,8.387519,Sandollar Productions Touchstone Pictures,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...
...,...,...,...,...,...,...,...,...,...
45448,Subdue,Drama Family,Rising and falling between a man and woman.,4.0,1.0,0.072051,,Rising and falling between a man and woman,Rising and falling between a man and woman. Dr...
45449,Century of Birthing,Drama,An artist struggles to finish his work while a...,9.0,3.0,0.178241,Sine Olivia,,An artist struggles to finish his work while a...
45450,Betrayal,Action Drama Thriller,"When one of her hits goes wrong, a professiona...",3.8,6.0,0.903007,American World Pictures,A deadly game of wits.,"When one of her hits goes wrong, a professiona..."
45451,Satan Triumphant,,"In a small town live two brothers, one a minis...",0.0,0.0,0.003503,Yermoliev,,"In a small town live two brothers, one a minis..."
45452,Queerama,,50 years after decriminalisation of homosexual...,0.0,0.0,0.163015,,,50 years after decriminalisation of homosexual...

In [70]:
df.iloc[0]['tags']

"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. Animation Comedy Family  Pixar Animation Studios"

#NLP

In [71]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [72]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [73]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [74]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #remove punctuation
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]
  #lemmatization
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [75]:
df['tags'] = df['tags'].apply(preprocess_text)

In [76]:
df['tags'][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement tristar picture teitler film interscope communication'

In [77]:
df = df.reset_index(drop=True)

In [78]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [79]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [80]:
tfidf = TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [81]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [83]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1744054 stored elements and shape (45447, 50000)>

#Cosine Similarity

In [85]:
from sklearn.metrics.pairwise import cosine_similarity

In [86]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie not found']

  idx = indices[title]
  sim_scores = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_scores.argsort()[::-1][1:n+1]
  return  df['title'].iloc[similar_idx]

In [91]:
recommend('Avatar',5)

13562     Dragonball Evolution
26547                 Avatar 2
11442                   Eragon
11918    Live Free or Die Hard
19175                The Watch
Name: title, dtype: object

In [92]:
import pickle

pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('indices.pkl', 'wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))